rt: './gookbang'

save_dir: './gookbang/pbe_aug_res'

mask_dir: './mask_sm.jpg'

gen_img: './ghillie_sd_gen.png'

model_path: 'pretrained_models/model.ckpt'

mp4_list: lst = ['A-15-1-(12).mp4', 'A-15-2-(51).mp4', 'A-12-1-(10).mp4', 'A-12-2-(11).mp4', 'A-12-2-(64).mp4', 
        'A-15-3-12.mp4', 'A-15-3-20.mp4', 'A-12-2-(102).mp4', 'B-sunrise-29.mp4', 'A-09-(25).mp4', 'A-12-2-(53).mp4', 
        'B-09-6.mp4', 'A-sunrise-28.mp4', 'B-15-19.mp4', 'A-12-2-(30).mp4', 'A-12-1-(18).mp4', 'A-15-3-29.mp4', 'A-15-2-(77).mp4', 
        'A-12-3-(10).mp4', 'A-12-1-(5).mp4', 'A-sunrise-11.mp4', 'A-sunrise-19.mp4', 'A-09-(23).mp4', 'B-12-1.mp4', 'A-12-1-(40).mp4', 
        'A-12-3-(19).mp4', 'A-15-1-(29).mp4', 'A-12-3-(62).mp4', 'A-09-(19).mp4', 'B-09-28.mp4', 'B-15-29.mp4', 'B-09-12.mp4', 
        'B-sunrise-18.mp4', 'A-09-(61).mp4', 'A-09-(48).mp4', 'A-09-(45).mp4', 'B-12-29.mp4', 'A-15-2-(2).mp4', 'A-09-(33).mp4', 
        'A-15-2-(31).mp4', 'A-12-1-(7).mp4', 'A-12-3-(1).mp4', 'A-12-3-(37).mp4', 'A-09-(20).mp4', 'B-12-4.mp4', 'A-15-2-(100).mp4', 
        'A-09-(29).mp4', 'B-12-11.mp4', 'A-15-1-(18).mp4']


